package Frames;

import Tablero.Tablero;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

public class MainMenu extends javax.swing.JFrame {
    private static Image fondo = Toolkit.getDefaultToolkit().createImage("mainMenu.jpg");
    
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnPlay = new javax.swing.JButton();
        jbtnLearning = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learning Chess");
        setBounds(new java.awt.Rectangle(300, 800, 579, 413));
        setMaximumSize(new java.awt.Dimension(579, 413));
        setMinimumSize(new java.awt.Dimension(579, 413));
        setPreferredSize(new java.awt.Dimension(579, 413));
        setResizable(false);
        setSize(new java.awt.Dimension(579, 413));
        getContentPane().setLayout(null);

        jbtnPlay.setText("Play 1v1");
        jbtnPlay.setFocusable(false);
        jbtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPlay);
        jbtnPlay.setBounds(120, 330, 110, 23);

        jbtnLearning.setText("Learning Center");
        jbtnLearning.setFocusable(false);
        jbtnLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLearningActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLearning);
        jbtnLearning.setBounds(310, 330, 130, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mainMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlayActionPerformed
        Tablero tablero = Tablero.crearTableroEstandar();
        System.out.println(tablero);
        
    }//GEN-LAST:event_jbtnPlayActionPerformed

    private void jbtnLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLearningActionPerformed
        // TODO add your handling code here:
        LearningCenter lerCen = new LearningCenter();
        lerCen.setVisible(true);
    }//GEN-LAST:event_jbtnLearningActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnLearning;
    private javax.swing.JButton jbtnPlay;
    // End of variables declaration//GEN-END:variables

    
}
